
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#ifndef __ATK_ENUM_TYPES_H__
#define __ATK_ENUM_TYPES_H__
/* enumerations from "atkcomponent.h" */
GType atk_scroll_type_get_type (void);
#define ATK_TYPE_SCROLL_TYPE (atk_scroll_type_get_type())
/* enumerations from "atkhyperlink.h" */
GType atk_hyperlink_state_flags_get_type (void);
#define ATK_TYPE_HYPERLINK_STATE_FLAGS (atk_hyperlink_state_flags_get_type())
/* enumerations from "atkobject.h" */
GType atk_role_get_type (void);
#define ATK_TYPE_ROLE (atk_role_get_type())
GType atk_layer_get_type (void);
#define ATK_TYPE_LAYER (atk_layer_get_type())
/* enumerations from "atkrelationtype.h" */
GType atk_relation_type_get_type (void);
#define ATK_TYPE_RELATION_TYPE (atk_relation_type_get_type())
/* enumerations from "atkstate.h" */
GType atk_state_type_get_type (void);
#define ATK_TYPE_STATE_TYPE (atk_state_type_get_type())
/* enumerations from "atktext.h" */
GType atk_text_attribute_get_type (void);
#define ATK_TYPE_TEXT_ATTRIBUTE (atk_text_attribute_get_type())
GType atk_text_boundary_get_type (void);
#define ATK_TYPE_TEXT_BOUNDARY (atk_text_boundary_get_type())
GType atk_text_granularity_get_type (void);
#define ATK_TYPE_TEXT_GRANULARITY (atk_text_granularity_get_type())
GType atk_text_clip_type_get_type (void);
#define ATK_TYPE_TEXT_CLIP_TYPE (atk_text_clip_type_get_type())
/* enumerations from "atkutil.h" */
GType atk_key_event_type_get_type (void);
#define ATK_TYPE_KEY_EVENT_TYPE (atk_key_event_type_get_type())
GType atk_coord_type_get_type (void);
#define ATK_TYPE_COORD_TYPE (atk_coord_type_get_type())
/* enumerations from "atkvalue.h" */
GType atk_value_type_get_type (void);
#define ATK_TYPE_VALUE_TYPE (atk_value_type_get_type())
#endif /* __ATK_ENUM_TYPES_H__ */

/* Generated data ends here */

